### ISSUE TITLE
DF Chat Enhancements: Roll Buttons No Longer Show

### ISSUE THREAD

**Issue by Larwck** [flamewave000/dragonflagon-fvtt#230]
**Module**
DF Chat Enhancements v3.5.1

**Describe the issue**
I updated from version 3.3.0 to the current latest 3.5.1 and the roll buttons were all gone, I restarted after changing the settings a few times to make sure but nothing worked. Restored to version 3.3.0 and they were back.

**To Reproduce**
Use 3.5.1, select the option for Roll Buttons in module settings, restart, see that they do not appear.

**Expected behavior**
Roll Buttons should replace the drop down menu and other buttons like they did previously, as expected when selecting that option in the settings.

**EDIT:** I just realised that I'm still using DnD5e 1.4.3 due to having an issue with the latest version, that could be why more than one of my modules are not working in their latest version, in which case ignore me.

**Comment by flamewave000** [comment]
There was a Roll Type conflict with another module. This was corrected in v3.4.0. What version of Foundry are you running? Because it was a simple CSS change that shouldn't care about what version your DnD5e system is at. Chat Enhance is a universal module with no system dependencies.

**Comment by Larwck** [comment]
Oh okay hmm. I'm on Foundry 0.8.9

**Comment by flamewave000** [comment]
ok, if you have a chance, could you try disabling all your other modules? If it works then there might be a conflict with another module.

If so, you can use [Find the Culprit!](https://foundryvtt.com/packages/find-the-culprit/) to figure out which module is conflicting with DFCE.

**Comment by Larwck** [comment]
Hey flamewave I just did this and the problem persisted even when all my other modules were disabled, apart from the ones required (DF Chat Enhancements, libWrapper, Library: Chat Commands). Both libWrapper and Library: Chat Commands are updated to latest versions.

![](https://i.imgur.com/F7sOII2.png?raw=true)

**Comment by flamewave000** [comment]
I'm going to close this one for now since I've updated this module to V9. If this issue still persists in V9 I can reopen the ticket.
